spring:
  output:
    ansi:
      enabled: always

  jpa:
    show-sql: true

  datasource:
    username: sa
    password: ""
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./data/taskManager

  h2:
    console:
      enabled: true